### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by voronianski** [Mordred/dokku-redirects-plugin#3]
My case - I have `myapp.com` deployed on dokku and I NEED `www.myapp.com` subdomain to point to the same app.

BUT I have `foo.myapp.com` (also deployed on dokku) and somehow `www.myapp.com` always points to this app instead of root..

I've tried this plugin, result - without any effect..

**Comment by Mordred** [comment]
Hi, can you post content of this files: REDIRECTS, nginx-redirects.conf  and /etc/nginx/conf.d/dokku-redirects.conf ?

**Comment by voronianski** [comment]
@Mordred 

REDIRECTS:

```
myapp.com=www.myapp.com
```

nginx-redirects.conf:

```
server {
  listen      [::]:80;
  listen      80;
  server_name myapp.com;
  return      301 http://www.myapp.com$request_uri;
}
```

/etc/nginx/conf.d/dokku-redirects.conf:

Says that there's no such file `cat: /etc/nginx/conf.d/dokku-redirects.conf: No such file or directory`..

```
/etc/nginx/conf.d# ls -a
.  ..  dokku.conf
```

**Comment by Mordred** [comment]
I think you didn't run `dokku plugins-install`, because when this plugin is installed, it creates that file:
https://github.com/Mordred/dokku-redirects-plugin/blob/master/install

**Comment by voronianski** [comment]
@Mordred thanks, manage to fixed my problem. But probably you need to consider changing docs for plugin:
- firstly I ran `dokku redirects:set myapp.com myapp.com=www.myapp.com` and saw that `myapp.com` redirects to `www.myapp.com` which was causing cycling redirects
- then I ran `dokku redirects:set myapp.com www.myapp.com=myapp.com` and that solved my problem perfectly

**Comment by Mordred** [comment]
You can send a pull request, if you want to make the README better.
